### ISSUE TITLE
Update doc with commands HurnRun and CurlToHurl and keep doc up to date.

### ISSUE THREAD

**Issue by 231tr0n** [ray-x/web-tools.nvim#13]
Hi and thankyou for this wonderful plugins. I really like the plugin a lot. But the issue is that i could not find HurlRun and CurlToHurl commands in the doc I had to check my wildmenu for that. It seems that the doc is really old and not updated. Is there any chance of updating it.

**Comment by ray-x** [comment]
The Readme.md contains documentation on HurlRun, which functions similarly to executing CurlToHurl. To use it, simply highlight the curl command and initiate CurlToHurl.

Additionally, contributions to enhance the documentation via a Pull Request are always welcome.

**Comment by 231tr0n** [comment]
Sure thank you i will try working on the docs in my free time and try contributing them. And once again thank you for this plugin it made my day that i could do api testing with hurl.
