### ISSUE TITLE
BrowserOpen try to visit "/mnt/c"  on windows with wsl running background

### ISSUE THREAD

**Issue by jyfzh** [ray-x/web-tools.nvim#3]
OS: win11
nvim: v0.7.2

```
Error executing vim.schedule lua callback: ...acker\start\web-tools.nvim/lua\web-tools\openbrowser.lua:27: Vim(lcd):E344: Can't find directory "/mnt/c" in cdpath
stack traceback:
        [C]: in function 'cmd'
        ...acker\start\web-tools.nvim/lua\web-tools\openbrowser.lua:27: in function 'open_cmd'
        ...acker\start\web-tools.nvim/lua\web-tools\openbrowser.lua:42: in function 'open'
        ...acker\start\web-tools.nvim/lua\web-tools\browsersync.lua:50: in function 'open_browser'

        ...acker\start\web-tools.nvim/lua\web-tools\browsersync.lua:75: in function 'open'
        ...acker\start\web-tools.nvim/lua\web-tools\browsersync.lua:58: in function 'callback'
        ...acker\start\web-tools.nvim/lua\web-tools\browsersync.lua:143: in function 'fn'
        vim/_editor.lua:384: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>
```
i notice in [openbrowser.lua](https://github.com/ray-x/web-tools.nvim/blob/master/lua/web-tools/openbrowser.lua#L26) line 26  `exists("$WSLENV")` will return 1, with wsl running in background  
i change it to `has("WSL")` ,i work on my windows, and i dont know it will work on other platforms

**Comment by ray-x** [comment]
I do not have a WSL machine to test
Do you mean I should do this:
```lua
if exists("$WSLENV")~=0 or exists("$WSL")~=0 then
  -- this is windows WSL
else....
```

**Comment by jyfzh** [comment]
i do some test.
## neovim on WSL
- has("windows")      return 1
- has("wsl")               return 1
- has("linux")            return  1
- exists("$WSLENV") return 1


## neovim on native windows:
- has("windows")     return 1
- has("wsl")              return 0
- has("linux")            return  0
- exists("$WSLENV")   return 0  (with WSL shutdown and restart windows terminal)
  in the condition, powershell dont have env "WSLENV"
- exists("$WSLENV")   return 1 (with WSL running in background and restart windows terminal and wait about 20 seconds to wait powershell flush env (? so strange) )
   in the condition, i run env check in powershell  `  env | grep -i wsl `  then it return ` WSLENV=WT_SESSION::WT_PROFILE_ID`
## i think just use the code below to check if is in wsl or not.
``` lua 
if has("wsl") then
    -- this is WSL
else...
```

i guess that the function ` exists( "$WSLENV") ` is check env is null or not

**Comment by ray-x** [comment]
Thanks for your help.
I pushed a new version.

**Comment by jyfzh** [comment]
# the problem not solve.
on native windows with wsl running background. it behave like before
### can we just skip to check WSLENV like below
```lua
local function open_cmd()
  local cmd = ':sclient !open'
  if vim.fn.has('wsl') == 1 then
    vim.cmd('lcd /mnt/c') -- note: this mean you are in WSL
    cmd = ':silent !cmd.exe /C start'
  elseif has('win32') ~= 0 or has('win32unix') ~= 0 then
    cmd = ':silent !start'
  elseif executable('xdg-open') == 1 then
    cmd = ':silent !xdg-open'
  elseif executable('open') == 1 then
    cmd = ':silent !open'
  else
    vim.notify(' platform not supported: ' .. util.os, vim.lsp.log_levels.ERROR)
  end
  return cmd
end
```

# and the command line has duplicate URL
i notic it is because [openbrowser.lua](https://github.com/ray-x/web-tools.nvim/blob/master/lua/web-tools/openbrowser.lua#L55-L59) line 53 round

<img width="930" alt="image" src="https://user-images.githubusercontent.com/77335030/199428289-7d4a8dba-ee7d-41ea-a0d7-f5249c67469f.png">

### by the way, i don't agree with the note in [openbrowser.lua](https://github.com/ray-x/web-tools.nvim/blob/master/lua/web-tools/openbrowser.lua#L28) line 28.  i think has("WSL") means is in wsl or not , but exists("$WSLENV") means wsl is running or not

**Comment by ray-x** [comment]
should been fixed, @jyf-111  could you check if it works?
