### ISSUE TITLE
BrowserOpen open a cmd on widnows

### ISSUE THREAD

**Issue by jyfzh** [ray-x/web-tools.nvim#4]
OS:windows11
nvim: v0.7.2

when i run BrowserOpen, it start a cmd windows and dont start browser automatically.
I have to click the `127.0.0.1:3000 ` in cmdline or type it in browser right way.
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/77335030/199246013-25409e14-3993-49f0-9020-29be37efce5b.png">

i notice [openbrowser.lua](https://github.com/ray-x/web-tools.nvim/blob/master/lua/web-tools/openbrowser.lua#L50) in line 50, the url is surrounded by ' ', 
if I change it to ` cmd = cmd .. ' ' .. vfn.escape(url, '#%!') `, it work on my windows

**Comment by ray-x** [comment]
should been fixed, @jyf-111  could you check if it works?

**Comment by jyfzh** [comment]
@ray-x something wrong with it 

i have already try to ```git reset 0b4765ae36f04280870abc3a2b49ffdf0e5cfaea```(Commits on Oct 22, 2022), to check if it's my mistake, but web-tools.nvim act the same as the last version.
---
after i put in ```BrowserOpen``` , web-tools.nvim act as follow:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/77335030/210163831-7eea674c-cacd-4e6d-9e50-9113c34c949f.png">

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/77335030/210163843-fa0f3525-0782-4745-8fde-e67adc1c87f8.png">

**Comment by ray-x** [comment]
As I update the code to 
https://github.com/ray-x/web-tools.nvim/blob/master/lua/web-tools/openbrowser.lua#L50
```lua
  if url then
    if util.is_windows() then
      cmd = cmd .. ' ' .. vfn.escape(url, '#%!')
    else
      cmd = cmd .. ' "' .. vfn.escape(url, '#%!') .. '"'
    end
    log(cmd)
    vim.cmd(cmd)
    return
  end
```
Does it mean you see a different error?

If you run brwoseropen directly in your cmd terminal, does it work?
```browser-sync start --server --watch --no-open --files .```

**Comment by jyfzh** [comment]
@ray-x no log output from neovim
---
if i run browser-sync in my cmd terminal
i tested several environment:
- native windows  and wsl on windows 
  if filename is index.html ,the browser return 404 not found
  if filename is not index.html ,the browser show ```Cannot GET /```
- ubuntu vps on azure
  browsersync directly in my cmd work perfectly

i think something wrong with browser-sync on windows

**Comment by ray-x** [comment]
I do not have a window to reproduce.  It looks to me `browser-sync ` does not work on window.

you mentioned 
`if I change it to cmd = cmd .. ' ' .. vfn.escape(url, '#%!'), it work on my windows`
Is it still the case?

Not so sure why wsl does not work either. Strange.

**Comment by jyfzh** [comment]
browser-sync@2.27.11  aslo does not work on my window
i try to roll back preview browser-sync, it also does not work.
i mentioned `if I change it to cmd = cmd .. ' ' .. vfn.escape(url, '#%!')` is to fix this issue `BrowserOpen open a cmd on widnows`
and on Nov 1, 2022, all works perfectedly, but now everything fail on windows,even on wsl

**Comment by jyfzh** [comment]
it seems that on 2023/3/24 browser-sync works fine on windows

---
i try old version of browser-sync, they all work final now. so strange😅
by the way, it`s a  nice plugin
