### ISSUE TITLE
Browser Sync is installed, fails to start, and accesses directories belonging to other node programs.

### ISSUE THREAD

**Issue by anoduck** [ray-x/web-tools.nvim#6]
Getting the weirdest errors while attempting to execute `BrowserOpen`. Upon execution of the command, the extension does open up the correct URL in the browser as it should, but fails to start, and outputs a chunk of errors. If I did not know better, I would assume that the extension is having difficulty locating the browsersync executable, regardless of it being within PATH and is stumbling as it searches.

First, it was outputting an error regarding an old cloud9 directory that was left abandoned. Now it is tripping over bitwarden-cli. 

![browser-sync_error](https://user-images.githubusercontent.com/9925396/209815520-4ed537cc-5a30-49c4-9415-dff6e25c141e.png)

**Comment by ray-x** [comment]
How about in your project run
`browser-sync start --server --watch --no-open --files index.html`
suppose the file you want to access is index.html

**Comment by anoduck** [comment]
@ray-x There is no question of whether browser-sync works in the terminal. It works just fine, and so does chokidar-cli. Which, for some reason, I have to work in conjunction with browser-sync to acquire the function of reloading the browser upon file changes. It just defeats the purpose of installing the plugin, is inconvenient, occupies a terminal tab, and requires hunting down the terminal every time I desire to run browser-sync, etc, etc, ...

**Comment by ray-x** [comment]
I am not so sure why the plugin watches `/home` folder instead of `/home/username/projectfile` folder.
When you open your HTML file it should pickup the working folder. I was wondering why not.
Before you run BrowserOpen
what is the result of `:pwd`

**Comment by anoduck** [comment]
@ray-x: I am running nvim from glrnvim inside of i3. The most common way I open nvim is the keymap `windows_key + n>`. Once open, the output of `:pwd` is `~/home/user`, and not as it should be, that is `/home/username/project_folder`. 

This is something that has always irritated me about my installation of nvim, everytime I have to open a file in the same folder, I still have to use the full path. Is there some setting that I am missing, or have misconfigured that tells nvim to chdir into the directory of the file that is open?

**Comment by anoduck** [comment]
@ray-x AND there you have it. The nvim option `vim.opt.autochdir` is `false` by default. You have to add `vim.opt.autochdir = true` to your config. Then everything works brilliantly. Thank you.

**Comment by ray-x** [comment]
Thanks for sharing that tip.
In fact I did not set autochdir. I use root plugins to set folder to the root of `.git` or project files.

**Comment by anoduck** [comment]
Not sure what that is, but cool... To be honest, I was using spacevim for several years, and got tired of its restrictions. Spacevim is sort of like windows, it can make you stupid, because it is already configured for you, and it is too easy to use. I saw how people were 'pimping up' their nvim configs on reddit, and had to get in on the action. So, there is a lot I am not familiar with.
