### ISSUE TITLE
How change PORT number for opening?

### ISSUE THREAD

**Issue by RAprogramm** [ray-x/web-tools.nvim#7]

**Comment by ray-x** [comment]
I allowed the arguments to pass in, you can add `--port 8888` to your argument.

**Comment by RAprogramm** [comment]
hello, thank you. but now it works only for BrowserOpen. 
but for BrowserPreview (if i already run my own server and want to open my html template) i had error `E488: Trailing characters: --port <port_number>`.

and another one, is there a possibility to auto close runned server when closing browser tab/window, or close tab/window when server close? Something like [markdown-preview](https://github.com/iamcco/markdown-preview.nvim)

**Comment by ray-x** [comment]
I pushed a update.
Also you do not need to specify --port in Preview command. The port is recorded.

As for auto close, it is beyond scope. Because markdown-preview implement a server for markdown, it accept close event. This plugin is wrapper for browser-sync and browser-sync does not support such feature.

**Comment by RAprogramm** [comment]
in case i opened golang server in port 8080, then i enter BrowserPreview command and page open in server 3000. but if i try to BrowserOpen --port 8080 -> will be open port 8081. (because port 8080 already in use)
that is why i think that need to specify --port in preview command

**Comment by ray-x** [comment]
The plugin will record the port been used, not the port you specified. In your case, it should open port 8081.

**Comment by RAprogramm** [comment]
https://user-images.githubusercontent.com/70325462/210302572-f894e9f6-574a-4d64-b1a9-5196c738c96c.mp4

**Comment by RAprogramm** [comment]
https://user-images.githubusercontent.com/70325462/210302884-6e0e599e-1a64-4dc2-aced-c0fb26c56dd0.mp4

**Comment by RAprogramm** [comment]
[Kazam_screencast_00000.webm](https://user-images.githubusercontent.com/70325462/210303411-3edfdbc8-af8d-42ba-bd3f-b2bc16681ebb.webm)

**Comment by ray-x** [comment]
Ok, I see what you mean. repo updated.

**Comment by RAprogramm** [comment]
![Screenshot from 2023-01-03 16-17-41](https://user-images.githubusercontent.com/70325462/210314062-b827d54a-0ea6-438f-a240-5a745bd74f05.png)

**Comment by ray-x** [comment]
wondering are you with latest version?
There is no reference to args on line 194

https://github.com/ray-x/web-tools.nvim/blob/5f4abd0346446a55e3c3eae472fd4a04a3a06a66/lua/web-tools/browsersync.lua#L193-L194

**Comment by RAprogramm** [comment]
[Screencast_00000.webm](https://user-images.githubusercontent.com/70325462/210315333-9b03e9ab-4b1b-4587-8a8e-3825b4710424.webm)

**Comment by ray-x** [comment]
I see what the issue is. I normally start up the server first. 
Just pushed another fix for it.

**Comment by RAprogramm** [comment]
[Screencast_00001.webm](https://user-images.githubusercontent.com/70325462/210320004-1783285e-c513-48ce-abe7-7b25bc5e7c54.webm)

**Comment by ray-x** [comment]
Hi @RAprogramm Could you check if the issue fixed?

**Comment by RAprogramm** [comment]
hello, it's not fixed, same on last video.
i can't open together my server and html by plugin

-------------------------------------------------------
perhaps this plugin not for it and i can  close issue
